### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by jokedurnez** [neuropower/neuropower-core#1]
Each function need full description.

**Comment by tsalo** [comment]
Hello Dr. Durnez, I don’t know if this is still something you wanted to get to at some point, but I recently forked this repository and added in numpydoc-format docstrings for most of the functions. It is still a work in progress, but all of the reformatting is done.

I added functions for generating the plots you create on the website and running the power analysis. I mean, I just took the code you have in the web app repository and compiled it in functions, but it could be useful for people interested in running power analyses offline.

I also simplified `cluster.PeakTable` and altered how the peak tables are generated to show x, y, and z coordinates in mm rather than matrix indices, which might make it easier for users to interpret them.

If you are still interested in improving the `neuropower` documentation, I’d love to open a PR and work on it.

**Comment by jokedurnez** [comment]
Hey !

That's really great work ! Thanks !

Unfortunately, I've also been working on a new version for the revision of the paper.  It started out with small little changes, which is why I never did this on this repository.  My newest code is here: https://github.com/neuropower/neuropower-validation-prospectiveRFT/tree/NeuroImage/Functions/neuropower_local.  

So we have 2 independent versions now:
- Mine has improved documentation and some statistical changes.  I'm atm finishing the paper and analyses that implements the newer code, so it's not ready yet to merge here.
- Yours has improved documentation and a lot of other cool functions.

I'm not really sure how to handle that.  Maybe I should make a branch here that is specifically for my analyses, and then I can later try to merge in my changes (when the analyses/paper are done).  In the meantime, it could be a good idea to merge in your changes, so you're welcome to submit a PR.  
(I left academia, so it's going a little slower on my side :-) ).  

Thanks so much for your work on this !

**Comment by jokedurnez** [comment]
Hi there ! I'm suuuuuper behind on all of this, but I merged your fork !
Hopefully this will give me a push to follow up again on this project :) Thanks !
